services:
  - type: worker
    name: husenov-ff-bot
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
