services:
  - type: web
    name: husenov-ff-bot      # только маленькие буквы, через дефис
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
